---
title: "Logical Thinking for Data Scientist"
author: '@ynakahashi'
date: "2018/12/18"
output:
  ioslides_presentation:
    logo: ~/Desktop/DSC_0030 20.08.51.jpg
    transition: faster
    widescreen: yes
  slidy_presentation: default
  beamer_presentation: default
---

Outline
========================================================

## Objective | *科学とは、論理的推論とは、ロジカルシンキングとは何かを学び、実務に活かす*
- Data "Scientist"なのに科学を知らないなんてあり得ない！
- クライアントを納得させる"ロジック"とは？
- DS PJにおけるロジカルシンキングの活用

## Target | *コンサルワークを行うパッケージユーザー*
- ***Data Scientist***（スタッフ〜PLレベル）
- 所属（大学や研究所 or 民間） × 主な利用（アルゴリズム開発 or アルゴリズム当てはめ）で四象限に切ったとき、民間かつアルゴ当てはめ
- どちらかと言えば機械学習エンジニアよりも統計モデラー
- データを活用し、意思決定をサポートする

## To Be | *Analytics Consultant*
科学的思想を尊重しつつビジネス上の課題に適した手法を選択し、PJを効率的に進めることができる

   - 効率的な仮説の立案
   - 網羅的なデータ収集
   - 納得感のある分析結果の提示



Contents
========================================================

## Contents
### 「**科学**」と「**ロジカルシンキング**」の2つを想定

## 1. 科学とは
### *Key Messages*
- 科学は明確に体系立てられたものではない
- でも「科学的な学問」と「そうでない学問」には小さくない差がある
- それらの差はどこにあるのだろうか？
- 我々が「科学的な」アプローチを取るためには、どんなポイントを押さえればよいのだろうか？

### *Key Takeaways*
- 「科学的である」ための条件となる指標をいくつか

## 2. ロジカルシンキング
### *Key Messages*
- 物事を俯瞰して捉える
- そのためのフレームワークを知る

### *Key Takeaways*
- aaa
- bbb
- ccc


1. 科学とは
========================================================
カール・ポパーの写真でも貼るか


## Agenda
- 1.1 科学的であるためのポイント
- 1.2 科学方法論

## 1.1 科学的であるためのポイント | *ウィーン学団以降の科学哲学の流れ*
1. 論理実証主義
2. クーンのパラダイム論（通常科学とパラダイム）、ポパーの反証可能性
3. ベイズ主義
4. 個別科学の時代

## 1.1 科学的であるためのポイント | *その間の重要な議論*
- ヒュームによる帰納（斉一性の原理）の批判
- ポパーによる反証可能性
- クーンのパラダイム論
- コントによる実在性
- カントによるクリティカルシンキング

## 1.2 科学方法論 | *科学的であるための****方法論***
- 「これぞ科学である」と言えるような方法はない（線引き問題）
- では何でも良いかと言われればそうでもない
- 科学的方法と言えるための種々の指標をなるべく満たす

## 1.2 科学方法論 | *科学的であるための****指標***
- 客観性
	- 定量性、測定可能性
	- 理論負荷性
		- 赤池や統数研伝統のモデル観（数理のめがね）
		- アヒルウサギ

## 1.2 科学方法論 | *科学的であるための****指標***
- 再現性
	- モデルの再構築を前提とする態度（実証主義）
- 統計的有意性
	- 頻度主義・尤度主義・ベイズ主義
	- それぞれの立場から見た確率
		- 主観確率と客観確率
  	 		- 信念としての確率
  	 		- コルモゴロフの公理系 
   		- 蓋然性、可能性
- 仮説、観察、考察

## 1.2 科学方法論 | *ご参考*
- 科学の文法（ピアソン）
- ミルの方法（ミル）


2. ロジカルシンキング
========================================================
デカルトの写真でも貼るか

## Agenda
- 2.1 論理の組み立て
- 2.2 DSへの適用事例

## 2.1 論理の組み立て | *ロジカルシンキングの基本は「**縦**」と「**横**」*
- クライアントからの不満
	- 本当にそうなの？　→　縦の論理構成が弱い
	- それだけなの？　→　横の網羅性が低い

## 2.1 論理の組み立て | ***縦****：論理的推論とロジックツリー*
- 論理的推論とは
	- 分析的推論（現在の知識の範囲のことしか言えない）
		- 演繹（デカルト）
	- 拡張的推論（現在の知識よりも多くのことが言える）
		- （枚挙的/経験的）帰納（ベーコン）
		- アナロジー
		- アブダクション（パース）
		- IBE（何だっけかな）

## 2.1 論理の組み立て | ***縦****：論理的推論とロジックツリー*
- ロジックツリー
	- Why So? So What?
	- KPIツリー

## 2.1 論理の組み立て | ***横****：MECE*
- 分析とは分けること
	- Analysisには分解という意味がある
	- 「どんな軸で分けるか」がキモ

## 2.1 論理の組み立て | ***横****：MECE*
- フレームワーク思考
	- 全体を網羅する
		- 絵を描く
	- 既存のフレームワークを組み合わせる
		- 縦×横のマトリックス
	- 既存のフレームワークを改良する
		- 〇〇 + α
			- RFM + M
			- 組織プロセステクノロジー + データ

## 2.1 論理の組み立て | *ピラミッドストラクチャ*
- 縦と横を組み合わせる

## 2.1 論理の組み立て | *Analysis for Synthesis*


## 2.2 DSへの適用事例
- ynakahashiの頭のなか
- もう少し応用
	- マクロな分析
	- ミクロな分析

## 2.2 DSへの適用事例 | *ynakahashiの頭のなか*
- Analyticsによる問題解決プロセス（四象限のやつ）
	- Business × Issue
	- Mathematics × Issue
	- Mathematics × Solution
	- Business × Solution 

## 2.2 DSへの適用事例 | *ynakahashiの頭のなか*
- Analytics Framework
	- 問題解決プロセス ×　分析目的
		- 説明重視：Analytics For Decision Making
		- 予測重視：Data Driven Decision Making
	- 意思決定プロセス ×　ロール・階層

## 2.2 DSへの適用事例 | *ynakahashiの頭のなか*
- データ分析マップ（工事中）
	- データのタイプ × タスク

## 2.2 DSへの適用事例 | *ynakahashiの頭のなか*
- モデルの発達
	- 回帰モデル〜DNN

## 2.2 DSへの適用事例 | *もう少し応用*
- マクロな分析
- ミクロな分析

## 2.2 DSへの適用事例 | *マクロな分析*
- Marketing Mix Modeling
	- 3C
- アンケート調査
	- AIDMA
- Change Management
	- 戦略 + イネーブラ（組織/プロセス/テクノロジー/データ）

## 2.2 DSへの適用事例 | *ミクロな分析*
購買予測モデルを考える

- 「***顧客が欲しがっている確率***」 × 「***その店で買う確率***」

## 2.2 DSへの適用事例 | *顧客が欲しがっている確率*
- デモグラ
- サイコグラフ

## 2.2 DSへの適用事例 | *顧客が欲しがっている確率*
- デモグラ(Static and/or Change)
	- 個人
		- 生物学的
		- 社会的
		- シコウ（思考、嗜好、志向）
	- 家族、血縁
	- コミュニティ
	- 上記の変化

## 2.2 DSへの適用事例 | *顧客が欲しがっている確率*
- サイコグラフ（Dynamic, 追跡可能な行動データから推測, RFM + M）
	- 日常的な行動
	- 突発的な行動
	- それらの比率

## 2.2 DSへの適用事例 | *その店で買う確率*
- その店で買うことを好む
- その店で買う価値がある

## 2.2 DSへの適用事例 | *その店で買う確率*
- その店で買うことを好む（ロイヤルティ）
	- ウォレットシェア
	- 継続期間

## 2.2 DSへの適用事例 | *その店で買う確率*
- その店で買う価値がある（比較優位性）
	- 4P
	- チャネルごとのハードル（UI、UX、店舗の近接度）
	- その店でしか買えない


言い足りないこと
========================================================
ヒュームの写真でも貼るか

## ヒュームによる因果への懐疑論
- ヒュームの議論は強力でなかなか勝てない

## ニュートン「われ仮説を作らず」
- ただしこの時代の仮説は思弁的なニュアンスを含んでいた
- 実際にニュートンは多分に仮説に基づいた考察を行っている

## アブダクションは仮説、帰納はパターン検知を担う
- データ分析の結果がユーザーの期待を超えられないのは**仮説構築力**が弱い
	- 仮説の変数化の段階でユーザーが想定していない変数がなければユーザーの期待は超えられない
	- ユーザーの仮説を変数に落とし込むだけでは、ユーザーの経験を帰納的に検証しているに過ぎない
	- そりゃそうだよね、で終わる
- 期待を超える結果が得られるパターンは？
	- 予期された結果と異なる
	- S社に当てはめると、似たようなテキストが、同じ主原因品番を「持たない」

## 統計に対する思想・哲学と論理的推論のマッピング
- 統計は学問としては数学よりも科学哲学に近い
- 統計と機械学習
	- 統計的仮説検定
		- 仮説形成的（アブダクション）
		- 統計的決定（ネイマンとワルド）
		- 因果推論
	- 統計モデルと機械学習
		- 枚挙的帰納的
		- 統計的推測（フィッシャー）
		- 予測

## 説明と解釈
- キャッチオール仮説とどう向き合う？
	- その仮説と同程度に説明が可能な対立仮説はきっと他にもある
	- 採択された結果は、反証されることで初めて価値となる
- 尤度主義とベイズ主義では評価しようとしている仮説が異なる
	- 尤度主義では2つの仮説の尤度比
	- ベイズ主義では事前確率による確信度の更新

## 赤池的モデル観
- モデルは作っては壊すもの、という態度
- 反証主義のフローチャートに沿ったもの

## 科学的発見
- 科学的発見には二種類ある
	- AがBであるということを発見した
	- AがBであるのはCが原因である
- なぜかの発見は仮説検証から得られる
	- アインシュタイン「経験をいくら集めても発明は生まれない」
		- 万有引力の法則は観察事実からの帰納的一般化によって導くことができない
		- 観察事実を説明するために創発・発明された
	- 問いと仮説は一体で、良い問いがなければ良い仮説は生まれない

## 定式化は、問いと仮説を立式すること
- 問いがY、仮説がX
